### PR TITLE
Deep Learning Vertexing DUNE

### PR DESCRIPTION
**Pull request by phuncr**

### CODE REVIEW

**Comment by lhwhitehead** [comment]
Just a general comment - why do you have the ConvNet class defined separately in two files?

**Comment by phuncr** [comment]
I have moved the ConvNet class definition into its own file.

**Review by PandoraPFA — COMMENTED** [review]
Hi Jhanzeb,

Thanks - the main thing to think about here is whether the individual file names are all suitable self-describing. It's a start that the model files are in a Deep_Learning_Vertexing_DUNE_Models location, but ideally the individual files (which will go out to dunepardata in the end) should be stamped with a specific larpandoracontent version (agreed that this version isn't fully confirmed yet), and a specific detector model (or maybe just DUNE FD, if applicable to both the full FD geometry and e.g. the 1x2x6). The word "my" in the model names is redundant too. So, a good idea to think about names throughout.

Thanks!

**Comment by AndyChappell** [comment]
Archived

**Pull request closed without merging**
